### ISSUE TITLE
EVERY package needs better docs

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/roadmap#7]
They all need to include information on what they inject into container/requests

**Comment by dashtodartlang** [comment]
I have a few suggestions on the documentation if you like.  I am only learning server side dart, so I would rely heavily upon you for editing my suggestions, but I can at least provide some basic skeleton on what I think would be helpful.  I commented on your G+ post a few days ago, so I wanted to follow up with an offer of help.

**Comment by thosakwe** [comment]
@rattaro Your input would *absolutely* be appreciated. Thank you so much for your help!

**Comment by dashtodartlang** [comment]
Not sure the best way to do this.  Please let me know what you prefer.  This is an edit of your wiki page:
https://github.com/angel-dart/angel/wiki/Without-the-Boilerplate

This is a rough draft.  I am just focussing more on the content rather than the style and location of the content.  I like your general documentation, but would like more detail.  I will defer to your style and preference with respect to how the documentation is ultimately created.

Any question is an unknown to me.  Nothing is rhetorical.  **** denotes that I think there is information here that I don’t know.

When to import angel, angel_common, angel_framework - in this case, we import angel_framework.  Under what circumstances do you import the others?  Not necessarily put this information here, but good to document somewhere.

This is from your page:
Angel app = new Angel() - The Angel API is manifested a class, and we need an instance of it to run our server.  app - by convention, the variable name ‘app’ should be used to instantiate Angel.  (is this true?  Should it be true?  I.e. should you from the very beginning, establish some conventions to simplify documentation or should you leave the flexibility to the developers?)
app.get("/", "Hello, world!");  App.get opens a stream, and listens, with the intention to accept data from the GET method from an HTML submission.  For example, for the html form:  <form method=”GET”></form>, the data from the html submission would go to the app.get method on the the Angel framework.  method=”POST” would go to the app.post method, and so forth.  Other methods include app.post, app.etc.  The methods are different in that:
		Get - what is different here.  How does these methods alter the effect of the response, if at all.  Are these just arbitrary terms?
		Post - ****
		Put - ****
                Delete -  ****
                Others? - maybe just a bookmark here to document later
	The first parameter “/” is the location of the URL (Uniform resource locator - basically the web site location) accessed through the html submission.  For example, for the html form:  <form action=”http://localhost:8080/something”></form>, the first parameter would be “/something” (app.get(“/something”, “Hello, world!”)).  The second parameter is the route.  A route is an action that is taken for any information received.  The received information is “routed” either back to the browser, or to a different section of the server.  Here, the information is received through the get method, and sends (or routes) a response “Hello, world!” (a String) back to the browser.  In some systems, it is the equivalent of write(“Hello, world!”).  Other possible choices for the second parameter include: 1.  anonymous function, 2. What else can be used here?
	The anonymous function is used when (under what circumstances is this used?).  It takes 2 optional parameters (RequestContext and ResponseContext).  Maybe a link for more information on this.

The response will automatically be encoded as JSON. (what does this mean?  The response seems to be sent as whatever you place:  String, List, JSON.)  Maybe a good place to place link for more information.

await app.startServer() - this starts the web server.  There are 2 optional parameters:  internet address, port.  In the (), if left blank, it defaults to:  InternetAddress 127.0.0.1 and port 8080.  For example, if you want to specify the internet address and port, it would look like this:  await app.startServer(192.168.1.100, 9000).  This is required and always placed at the very end of the code (correct?).

You might consider wrapping this in a call to runZoned, so your server does not crash on errors.  (Please clarify.  What is a runZoned?  How does this work?  Maybe provide link here.)

**Comment by thosakwe** [comment]
Thanks a lot for these suggestions. I tell you, these never ran across my mind once. I didn't realize how much detail the docs were lacking.

**Comment by dashtodartlang** [comment]
That's because you are no longer a beginner.  It's so easy to forget what
it was like.  I tried to offer suggestions for the rest, but I kept hitting
blocks that I didn't understand.  I'll send them to you later.
